DeskAspMvc/Areas/Admin/Controllers/Desk2Controller.cs
using DeskAspMvc.Data;
using DeskAspMvc.Models.dto;
using DeskAspMvc.services.DTO;
using DeskAspMvc.services.Services2;
using DeskAspMvc.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace DeskAspMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("Administrator")]
    public class Desk2Controller : Controller
    {
        private DeskService _deskService { get; set; }
        private LocationService _locationService { get; set; }
        public Desk2Controller(DeskService deskService, LocationService locationService)
        {
            this._deskService = deskService;
            this._locationService = locationService;
        }
        public IActionResult Index()
        {
            var lst = this._deskService.GetListWithLocation();
            return View(lst);
        }
        private SelectList getLocations()
        {
            var selectlst = new SelectList(_locationService.GetList(), "Id", "Name");

            SelectListItem selListItem = new SelectListItem() { Value = "", Text = "no location" };
            List<SelectListItem> newList = new List<SelectListItem>(selectlst);
            newList.Insert(0,selListItem);
            return new SelectList(newList, "Value", "Text", null); ;
        }
        public IActionResult Create()
        {     
            ViewBag.locationKey = getLocations();
            return View();
        }
        [HttpPost]
        
        public IActionResult Create(Desk entry)
        {
            if(!ModelState.IsValid)
            {
                ViewBag.locationKey = getLocations();
                return View(entry);
            }
            var status = _deskService.Create(entry);
            this.ViewBag.Status = status;
            var lst = this._deskService.GetListWithLocation();
            ViewBag.createid = entry.Id;
            return View("Index", lst);
        }

        public IActionResult Edit(int? id)
        {
            var status = this._deskService.DoesExist(id);
            if (status.hasSucceeded == false)
            {
                ViewBag.Status = status;
                var lst = this._deskService.GetList();
                return View("Index", lst);
            }
            ViewBag.locationKey = getLocations();
            return View(this._deskService.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Desk entry)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.locationKey = getLocations();
                return View(entry);
            }
            var status = _deskService.Edit(entry, entry.Id);
            ViewBag.Status = status;
            ViewBag.editid = entry.Id;
            return View("Index", this._deskService.GetListWithLocation());
        }

        public IActionResult Delete(int? id)
        {
            var status = _deskService.Delete(id);
            ViewBag.Status = status;
            return View("Index", this._deskService.GetList());
        }        
    }
}

DeskAspMvc/Areas/Admin/Controllers/Location2Controller.cs
using DeskAspMvc.Data;
using DeskAspMvc.services;
using DeskAspMvc.services.Services2;
using DeskAspMvc.Models.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.AspNetCore.Authorization;

namespace DeskAspMvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize("Administrator")]
    public class Location2Controller : Controller
    {

        private ApplicationDbContext _context { get; set; }
        private LocationService _service { get; set; }
        public Location2Controller(ApplicationDbContext context,LocationService service)
        {
            this._context = context;
            this._service = service;
        }
        public IActionResult Index()
        {
            var lst = this._service.GetList();
            return View(lst);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Location entry)
        {
            if(!ModelState.IsValid)
            {
                return View(entry);
            }
            var status = _service.Create(entry);
            this.ViewBag.Status = status;
            var lst = this._service.GetList();
            ViewBag.createid = entry.Id;
            return View("Index", lst);
        }


        public IActionResult Edit(int? id)
        {
            var status = this._service.DoesExist(id);
            if(status.hasSucceeded==false)
            {
                ViewBag.Status = status;
                var lst = this._service.GetList();
                return View("Index",lst);
            }
            return View(this._service.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(Location entry)
        {
            if(!ModelState.IsValid)
            {
                return View(entry);
            }
            var status = _service.Edit(entry, entry.Id);
            ViewBag.Status = status;
            ViewBag.editid = entry.Id;
            return View("Index", this._service.GetList());
        }

        public IActionResult Delete(int? id)
        {
            var status = _service.Delete(id);
            ViewBag.Status = status;
            return View("Index", this._service.GetList());
        }
    }
}

DeskAspMvc/Areas/Admin/Controllers/ReservationController.cs
using DeskAspMvc.Models.Models;
using DeskAspMvc.services.Services2;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DeskAspMvc.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize("Administrator")]
    public class ReservationController : Controller
    {

        private ReservationService _reservationService { get; set; }
        public ReservationController(ReservationService reservationService)
        {
            this._reservationService = reservationService;
        }
        public IActionResult Index()
        {
            var list = this._reservationService.GetList();
            return View(list);
        }
        public IActionResult Delete(int? id)
        {
            var status = this._reservationService.Delete(id);
            var list = this._reservationService.GetList();
            ViewBag.Status = status;
            return View("Index", list);

        }
    }
}

DeskAspMvc/Areas/Employee/Controllers/AdminAccessController.cs
using DeskAspMvc.Data;
using DeskAspMvc.services.AuthorizeServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace DeskAspMvc.Areas.Employee.Controllers
{

    [Area("Employee")]
    public class AdminAccessController : Controller
    {
        private MyAuthorizeService _myAuthorizationService { get; set; }
        public AdminAccessController(
            MyAuthorizeService myAuthorizeService
            )
        {
            this._myAuthorizationService = myAuthorizeService;
        }

        public async Task<IActionResult> Revoke()
        {
            string username = User.Identity.Name;
            await this._myAuthorizationService.RemoveFromRole(username);
            return View();
        }
        public async Task<IActionResult> Gain()
        {
            string username = User.Identity.Name;
            await this._myAuthorizationService.AddToAdminRole(username);
            return View();
        }

        [Authorize(Policy = "Administrator")]
        public IActionResult AdminTask()
        {
            return View();
        }
    }
}

DeskAspMvc/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeskAspMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeskAspMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">DeskAspMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="row">    
        <div class="col-2">
            <ul>
                <li class="nav-item">@Html.ActionLink("list of locations", "Index", "Location2", new { area = "Admin"}, new { @class="border-2 nav-link bg-light text-primary border border-primary rounded text-white-hover bg-primary-hover" })</li>
                <li class="nav-item ">@Html.ActionLink("list of desks", "Index", "Desk2", new { area = "Admin"}, new { @class="border-2 nav-link bg-light text-primary border border-primary rounded" })</li>
                <li class="nav-item">@Html.ActionLink("list of reservation for admin", "Index", "Reservation", new { area = "Admin"}, new { @class="border-2 nav-link bg-light text-primary border border-primary rounded" })</li>
                <li class="nav-item">@Html.ActionLink("gain admin privileges", "Gain", "AdminAccess", new { area = "Employee"}, new { @class="border-2 nav-link bg-light text-danger border border-danger rounded" })</li>
                <li class="nav-item">@Html.ActionLink("revoke admin privileges", "Revoke", "AdminAccess",new { area = "Employee"},  new { @class="border-2 nav-link bg-light text-danger border border-danger rounded" })</li>
                <li class="nav-item">@Html.ActionLink("test if you have admin privileges", "AdminTask", "AdminAccess",new { area = "Employee"}, new { @class="border-2 nav-link bg-light text-success border border-success rounded" })</li>
                <li class="nav-item">@Html.ActionLink("create book reservation", "Create", "Reservation2", new { area = "Employee"}, new { @class="border-2 nav-link bg-light text-success border border-success rounded" })</li>
                <li class="nav-item">@Html.ActionLink("list of your reservations", "Index", "Reservation2", new { area = "Employee"}, new { @class="border-2 nav-link bg-light text-success border border-success rounded" })</li>
            </ul>
        </div>
        <div class="col-10">
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeskAspMvc - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Selectize.js"></script>
    <link rel="stylesheet" href="~/css/selectize.bootstrap3.css" />
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("css", required: false)
</body>
</html>